config/routes.rb
Followindy2::Application.routes.draw do |map|
  resources :feeds do
    collection do
      get :indystar_feed_maker
    end
  end
    

  
  match 'things/add' => 'things#create'
  
  match 'things/thanks' => 'things#thanks'
  
  match 'about' => 'things#about'
  
  root :to => "things#index"
  
  resources :sources

  resources :things
  
  resources :tags
  
  resources :search, :only => :index
  

end

app/models/thing.rb
class Thing < ActiveRecord::Base
  
  # belongs_to :source
  belongs_to :feed
  has_one :origin, :class_name => "Source", :primary_key => "source_id", :foreign_key => "id"
  
  accepts_nested_attributes_for :origin
  
  before_validation :extract, :sourcify, :tag_this, :dupe_check, :on => :create
  
  before_save :clean
  
  define_index do
     indexes :title
     indexes :summary
     indexes :extended_body
     indexes :tag_list 
     indexes origin.slug, :as => :source_slug
    
     has :id
     has "CAST(DATE(things.created_at) as datetime)", :as => :date, :sortable => true, :facet => true, :type => :datetime
     has :created_at, :sortable => true
     
  end 
  
  
  def source
    origin.blank? ? feed.source : origin
  end
    
  def self.delayed_save(options={}, feed=nil)
    self.create(options)
    # if feed
    #   self.feed = Feed.find_by_url(feed)
    #   self.save!
    # end
  end
  
  def tags
    tag_list.split(", ")
  end
  
  def tag_this
    self.tag_list = SemanticExtraction.find_keywords(extended_body).collect{|t| t.parameterize.gsub("-", " ")}.join(", ")    
  end
  
  def categories
    feed.blank? ? [] : feed.categories.split(",")
  end
      
  
  def self.hijack_update(link, attributes)
    attributes[:source_id] = Source.where(:slug => link.match(/\w{3,5}:\/\/(\w*\.|)(.+)\.\w{1,3}\/.*/)[2].gsub(".", "_")).first.id if attributes[:source_id].blank?
    attributes[:title] = self.fetch_title(link) if attributes[:title].blank?
    if thing = Thing.where(["(link = ? or title = ?) and source_id = ?", link.gsub(/&t=.+$/, ""), attributes[:title], attributes[:source_id]]).first
      thing.update_attributes(attributes)
      # thing.tag_this
      thing.save!
      return thing
    else
      return false
    end
  end
  
  def sourcify
    if origin.blank?
      matches = link.match(/\w{3,5}:\/\/(\w*\.|)(.+)\.\w{1,3}\/.*/)
      if matches[1].blank? || matches[1] == "www."
        root = matches[2].gsub(".", "_")
      else
        root = (matches[1] + matches[2]).gsub(".", "_")
      end
      unless source = Source.where(:slug => root).first
        source = Source.create(:slug => root, :name => root.capitalize, :home_url => link.match(/(\w{3,5}:\/\/.+\.\w{2,4}\/).*/)[1])
      end
      self.source_id = source.id
    end
  end
  
  # Attempts to extract the extended_body, body and title from an arbitrary URL. By necessity, extended_body is very rough right now.
  # However, in limited testing, so far it is nailing the primary content div.
  def extract
    if summary.blank? || title.blank?
      # http = RubyTubesday.new
      # raw = http.get(link)
      c = Curl::Easy.perform(self.link) do |curl|
        curl.follow_location = true
      end
      data = Nokogiri::HTML(c.body_str)
      no_body = false
    end
    if extended_body.blank?
      self.extended_body = Sanitize.clean(SemanticExtraction::AdHoc.extract_text(link))
    end
    if summary.blank?
      if meta_desc = data.css("meta[name='description']").first 
        content = meta_desc['content']
      elsif no_body
        content = "No summary available"
      else
        content = Nokogiri::HTML(extended_body)
        content = content.css("p").first.text
      end
      self.summary = content
    end
    if title.blank?
      self.title = data.css("title").first.children.first.to_s
    end
  end
  
  def self.fetch_title(link)
    c = Curl::Easy.perform(link) do |curl|
      curl.follow_location = true
    end
    data = Nokogiri::HTML(c.body_str)
    data.css("title").first.children.first.to_s
  end
  
  def clean
    self.link = link.gsub(/&t=.+$/, "")
    self.title = Sanitize.clean(self.title)
    self.summary = Sanitize.clean(self.summary)
  end
  
  def related(limit=100)
    query = "(" + tags.collect{|u| '"' + u + '"'}.join(" & ") + ")"
    query << " | "
    query << "(" + tags.collect{|u| '"' + u + '"'}.join(" | ") + ")"
    date1 = (created_at - 2.weeks)
    date2 = (created_at + 2.weeks)
    search = Thing.search(
     query,
     :without => {:id => self.id},
     :with => {:created_at => date1..date2},
     :match_mode => :extended, 
     :sort_mode => :extended,
     :limit => limit,
     :order => "@weight DESC"
    )
    @search = []
    unless search.blank?
      search.each_with_weighting do |p, weight|
        if weight >= 9514
          @search << p
        end
      end
    end
      
       # tags_to_find = tags.collect { |t| t.name }
       # 
       #       exclude_self = "things.id != #{self.id} AND"
       #       @search = Thing.paginate(
       #         :select     => "things.*, COUNT(tags.id) AS count", 
       #         :from       => "things, tags, taggings",
       #         :conditions => ["#{exclude_self} things.id = taggings.taggable_id AND taggings.taggable_type = 'Thing' AND taggings.tag_id = tags.id AND tags.name IN (?) and COUNT(tags.id) > 0", tags_to_find],
       #         :group      => "things.id",
       #         :order      => "count DESC",
       #         :per_page   => per_page,
       #         :page       => page
       #         ) 
       # @search = WillPaginate::Collection.create(page, per_page, search.total_entries) do |pager|
       #   pager.replace(@search)
       # end
       return @search
 
  end
  
  def related_count(uncached=false)
    if uncached || cached_related_count.blank?
      self.cached_related_count = related.length
      self.save!
      return cached_related_count
    else
      return cached_related_count
    end
  end
  
  def self.refresh_related_counts
    Thing.where("created_at > #{2.weeks.ago}").find_each do |thing|
      thing.cached_related_count = related.count
      thing.save!
    end
  end
  
  def self.find_tagged_with(tag, this_page=1)
    @things = Thing.search(
      "@tag_list '#{tag}'",
      :match_mode => :extended,
      :page => this_page,
      :order => :created_at,
      :sort_mode => :desc
    )
  end
  
  def self.tag_by_days(tag)
    @dates = Thing.facets(
      "@tag_list '#{tag}'",
      :match_mode => :extended
    )
    return fill_days(@dates[:date].inject({}){|memo,(k,v)| memo[k.to_date] = v; memo})
  end
  
  def self.source_by_days(source)
    @dates = Thing.facets(
      "@source_slug #{source.slug}",
      :match_mode => :extended
    )
    return fill_days(@dates[:date].inject({}){|memo,(k,v)| memo[k.to_date] = v; memo})
  end
  
  def self.search_by_days(query)
    @dates = Thing.facets(
      query,
      :match_mode => :extended
    )
    return fill_days(@dates[:date].inject({}){|memo,(k,v)| memo[k.to_date] = v; memo})
  end
  
  def to_json(options={})
    options = options.merge(:except => :extended_body)
    super(options)
  end
  
  private
  
  def self.fill_days(dates)
    source = Source.find_by_slug("wthr")
    range = Thing.order("created_at ASC").where("source_id != #{source.id} and created_at is not null").first.created_at.to_date..Thing.order("created_at DESC").first.created_at.to_date
    range.each do |day|
      dates[day] = 0 unless dates[day]
    end
    return dates.collect{|key, value| OpenStruct.new(:date => key, :value => value)}.sort_by{|u| u.date}
  end
  
  def dupe_check
    if thing = Thing.where(["(link = ? or title = ?) and source_id = ?", link.gsub(/&t=.+$/, ""), title, source_id]).first
      return false
    end
  end
  
end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  respond_to :html, :json, :atom
  
  protect_from_forgery :except => :create
  
  def create
    if params["secret"] && params["secret"] == "srgesthreth"
      link = params["thing"].delete("link")
      if (@thing = Thing.find_by_link(link.gsub(/&t=.+$/, ""))) && @thing != false
        if params["automated"] && params["automated"] == "true"
          render :nothing => true
        else
          redirect_to edit_thing_path(@thing)
        end
      else
        if params["automated"] && params["automated"] == "true"
          if params["delayed"] && params["delayed"] == "true"
            Thing.send_later(:delayed_save, params["thing"].merge("link" => link), params["feed"])
          else
            @thing = Thing.create!(params["thing"].merge("link" => link))
          end
          render :nothing => true
        else
          @thing = Thing.create!(params["thing"].merge("link" => link))
          redirect_to edit_thing_path(@thing)
        end
      end
    else
      render :nothing => true
    end
  end
  
  def edit
    @thing = Thing.find(params[:id])
    @source = @thing.origin
    render :layout => "minimal"
  end
  
  def update
    @thing = Thing.find(params[:id])
    @thing.update_attributes(params[:thing])
    redirect_to :layout => "minimal", :action => "thanks"
  end
  
  def show
    @thing = Thing.find(params[:id])
    respond_to do |format|
      format.html{ 
        @things = @thing.related
        @page_title = "Related to \"#{@thing.title}\""
        render :action => :index
      }
      format.json {
        render :json => @thing.to_json(:methods => :related)
      }
    end
  end
  
  def thanks
    render :layout => "minimal"
  end
  
  
  
  def index
    @things = Thing.order("created_at DESC").paginate(:page => params[:page] || 1)
    respond_with(@things)
  end
end

app/helpers/things_helper.rb
module ThingsHelper
end

app/views/things/_thing.html.haml
.entry.clearfix
  .meta
    %h6
      %a.favicon{:href => source_path(thing.source)}
        %img{:src => thing.source.home_url + "/favicon.ico"}
      Published 
      = time_ago_in_words(thing.created_at)
      ago
    .tag_list
      = raw(thing.tags.collect{|tag| link_to tag, tag_path(tag)}.to_sentence(:last_word_connector => " and "))
  .main
    %h3
      = link_to raw(thing.title), thing.link
    %p
      = raw(awesome_truncate(thing.summary, 400))
    %ul.meta
      %li
        = link_to "Read More", thing.link
      - unless thing.related_count.to_s == "0"
        %li
          = link_to "Related (#{thing.related_count})", thing_path(thing)
      :javascript
        instapaper_embed('#{thing.link}', '#{escape_javascript(thing.title)}', '#{escape_javascript(thing.summary)}');

app/views/things/about.html.haml
%h2
  About Follow Indy

#about  
  <p>FollowIndy is an aggregate picture of what's being written about by Indianapolis-area news organizations and individuals.</p>
  <p>It attempts to find and organize everything so users can try to discover patterns in news coverage and public attention of particular topics.</p>
  %p
    = link_to "Chris Vannoy", "http://chrisvannoy.com" 
    is the (lack of) brains behind this project.
  <p>All content is copyright of its original owner and FollowIndy makes no claim to ownership of any of said content.</p>    
  %p
    FollowIndy displays only information that is available through public APIs or RSS feeds. If you represent a content owner and would not like your content to appear here, 
    = mail_to "chris@followindy.com", "contact us", :subject => "Hey, I don't want my stuff on FollowIndy.com!" 
    and we'll get it removed.  
  %p
    You can find out still more information about FollowIndy on 
    = link_to "its blog", "http://blog.followindy.com/" 
    or via <a href="http://twitter.com/FollowIndy">Twitter</a>.

app/views/things/edit.html.haml
- semantic_form_for(@thing) do |form|
  - form.inputs :name => "A new thing" do
    = form.input :title
    = form.input :summary
    = form.input :tag_list

  = form.inputs :name, :description, :home_url, :for => :origin, :name => "Source"
    
  - form.buttons do
    = form.commit_button

app/views/things/index.html.haml
- if @page_title
  %h2
    = @page_title
    
- if defined?(@by_date)
  #graph
  = raw(chart("graph", { "Tag Activity Timeline" => { :collection => @by_date, :x => :date, :y => :value, :options => {:color => "#2f63ac"} }}, {:legend => {:show => false}, :lines => {:fill => true, :lineWidth => 4}, :grid => {:show => false, :borderWidth => 0, :borderColor => "#ffffff", :tickColor => "#ffffff"}}))

- if @things.respond_to?(:total_pages)
  = will_paginate(@things, :previous_label => "&laquo; Later", :next_label => "Earlier &raquo;")

= render :partial => "things/thing", :collection => @things

- if @things.respond_to?(:total_pages)
  = will_paginate(@things, :previous_label => "&laquo; Later", :next_label => "Earlier &raquo;")

app/views/things/thanks.html.haml
%h1
  Thanks